version: "3.9"
services:
  mysql8:
    container_name: mysql8_ofg
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: ofg_db
    volumes:
      - data-mysql-ofg:/var/lib/mysql
    restart: always
    networks:
      - spring

volumes:
  data-mysql-ofg:
    name: data-mysql-ofg

networks:
  spring:
    name: spring
